name: flutter_finance
description: Personal finance management mobile application
publish_to: 'none'
version: 1.0.3+3

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Networking
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.4.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

  # Security
  flutter_secure_storage: ^9.2.2

  # UI/UX
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0

  # Navigation
  go_router: ^14.2.7

  # Utilities
  intl: ^0.19.0
  logger: ^2.4.0
  uuid: ^4.4.2
  equatable: ^2.0.5

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0

  # Testing
  mockito: ^5.4.4

flutter:
  uses-material-design: true
